# 证件查找方向有RIGHT、LEFT、DOWN、UP四种，另外SAME表示目标与关键字位于同一字段中。
# SAME可以单独作为查找方向，只在关键字所在字段中进行匹配。
# 其余四个方向都会将SAME作为补充查找，比如，RIGHT相当于RIGHT & SAME。

证件:
 特种设备使用登记证:
  证件名: 特种设备使用登记证
  日期: [发证日期, RIGHT, '(\d{4})年(\d{2})月(\d{2})日']

 中华人民共和国道路运输证:
  证件名: 中华人民共和国道路运输证
  日期: [有效, DOWN, '(\d{4})年(\d{2})月']
  经营范围: [经营, RIGHT, '危险货物|危险化学品']
  车牌: [车辆号牌, RIGHT, '^[\u4E00-\u9FA5][A-Z][A-Z0-9]{4}[A-Z0-9挂学警港澳]$']

 道路危险货物运输驾驶员证:
  证件名: [从业, RIGHT, '(危险|危驾|危货).*驾']
  日期: [ 有效, RIGHT, '(\d{4})-(\d{2})-(\d{2})' ]
  姓名: [ 姓名, RIGHT, '((?<=姓名)[\u4E00-\u9FA5]{2,4})|(^[\u4E00-\u9FA5]{2,3}$)']

 危险货物运输押运人员证:
  证件名: [从业, RIGHT, '(危险|危驾).*押运']
  日期: [有效, RIGHT, '(\d{4})-(\d{2})-(\d{2})']
  姓名: [姓名, RIGHT, '((?<=姓名)[\u4E00-\u9FA5]{2,4})|(^[\u4E00-\u9FA5]{2,3}$)']
  身份证号: [身份证件号, RIGHT, '[1-9]\d{5}(18|19|20)\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\d{3}[0-9Xx]']

 中华人民共和国机动车驾驶证:
  证件名: 中华人民共和国机动车驾驶证
  日期: [有效, RIGHT, '(?<=至)(\d{4})-(\d{2})-(\d{2})']
  姓名: [姓名, RIGHT, '((?<=姓名)[\u4E00-\u9FA5]{2,4})|(^[\u4E00-\u9FA5]{2,3}$)']

 中华人民共和国机动车行驶证:
  证件名: 中华人民共和国机动车行驶证
  日期: [检验有效, RIGHT, '(\d{4})年(\d{2})月']
  车牌: [号牌, RIGHT, '^[\u4E00-\u9FA5][A-Z][A-Z0-9]{4}[A-Z0-9挂学警港澳]$']


匹配:
 车牌: [中华人民共和国道路运输证, 中华人民共和国机动车行驶证]
 人脸: [道路危险货物运输驾驶员证, 中华人民共和国机动车驾驶证, 危险货物运输押运人员证]