证件:
 特种设备使用登记证:
  证件名: 特种设备使用登记证
  日期: [发证日期, RIGHT, '(\d{4})年(\d{2})月(\d{2})日']

 中华人民共和国道路运输证:
  证件名: 中华人民共和国道路运输证
  日期: ['有效期.*', DOWN, '(\d{4})年(\d{2})月']
  经营范围: [经营范围, RIGHT, '危险货物|危险化学品']
  车牌: [车辆号牌, RIGHT, '^[\u4E00-\u9FA5][A-Z][A-Z0-9]{4}[A-Z0-9挂学警港澳]$']

 危险货物运输押运人员证:
  证件名: [从业资格, RIGHT, '(危险|危驾).*押运']
  日期: ['有效期限|有效期至', RIGHT, '(\d{4})-(\d{2})-(\d{2})']
  姓名: [姓名, RIGHT, '^[\u4E00-\u9FA5]{2,4}$']
  身份证号: [身份证件号, RIGHT, '^[1-9]\d{5}(18|19|20|(3\d))\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\d{3}[0-9Xx]$']

 中华人民共和国机动车驾驶证:
  证件名: 中华人民共和国机动车驾驶证
  有效期: ['有效期限', RIGHT, '(\d{4})-(\d{2})-(\d{2})']
  姓名: [姓名, RIGHT, '^[\u4E00-\u9FA5]{2,4}$']

 中华人民共和国机动车行驶证:
  证件名: 中华人民共和国机动车行驶证
  日期: [检验有效期, SAME, '(\d{4})年(\d{2})月']
  车牌: [号牌, RIGHT, '^[\u4E00-\u9FA5][A-Z][A-Z0-9]{4}[A-Z0-9挂学警港澳]$']

 道路危险货物运输驾驶员证:
  证件名: [从业资格, RIGHT, '(危险|危驾).*驾驶']
  日期: [ '有效期限|有效期至', RIGHT, '(\d{4})-(\d{2})-(\d{2})' ]
  姓名: [ 姓名, RIGHT, '^[\u4E00-\u9FA5]{2,4}$']

匹配:
 车牌: [中华人民共和国道路运输证, 中华人民共和国机动车行驶证]